Improvements to the code

diff --git a/archlinux-sbct b/archlinux-sbct
--- a/archlinux-sbct
+++ b/archlinux-sbct
@@ -10,10 +10,8 @@
 #
 # check if running as root
 #
-if [ "$(whoami)" != "root" ]; then
-    echo "This script must be executed as root."
-    exit 0
-fi
+[ "$(whoami)" != "root" ] && \
+    echo "This script must be executed as root." && exit 1
 
 # Verify Arch Linux is running
 if [ ! -x /usr/bin/pacman ]; then
@@ -24,34 +22,21 @@ if [ ! -x /usr/bin/pacman ]; then
         os=$(lsb_release -ds | sed 's/"//g')
 fi
 
-if [ "${os}" != "Arch Linux" ]; then
-    echo "You must be using Arch Linux to execute this script."
-    exit 1
-fi
+[ "${os}" != "Arch Linux" ] && \
+    echo "You must be using Arch Linux to execute this script." && exit 1
 
-welcome() {
-    clear
-    pacman -S figlet --noconfirm --needed > /dev/null 2>&1
-    figlet -c "Arch Linux"
-    figlet -c "SBCT"
-    pacman -Rncsd figlet --noconfirm > /dev/null 2>&1
-    printf "\n\nWelcome to Arch Linux SBCT!\nKernel version: `uname -r`\n"
-}
+[ -z `pacman -Qqe | grep "preloader-signed"` ] && \
+    echo "Please install this package to continue: preloader-signed"
 
-root() {
-    dependencies="preloader-signed"
-    if [ -z `pacman -Qqe | grep "${dependencies}"` ]; then
-        echo "\n:: Installing package: '${dependencies}'..."
-        yay -S "${dependencies}" --noconfirm --needed > /dev/null 2>&1 || \
-            echo "Error installing package ${dependencies}"
-    fi
-    printf "\n:: Copying file HashTool.efi to /boot/EFI/BOOT/..." && \
-    cp /usr/share/preloader-signed/HashTool.efi /boot/EFI/BOOT/ && echo " done" && \
-    printf "\n:: Copying file systemd-bootx64.efi to /EFI/BOOT/loader.efi..." && \
-    cp /boot/EFI/systemd/systemd-bootx64.efi /boot/EFI/BOOT/loader.efi && echo " done" && \
-    printf "\n:: Copying file PreLoader.efi to /boot/EFI/BOOT/BOOTx64.efi..." && \
-    cp /usr/share/preloader-signed/PreLoader.efi /boot/EFI/BOOT/BOOTx64.efi && echo " done" || echo "Error"
-}
-# Initialize script functions in this order
-welcome
-root
+printf "\n:: Copying file HashTool.efi to /boot/EFI/BOOT/... "
+cp /usr/share/preloader-signed/HashTool.efi /boot/EFI/BOOT/
+[ $? = "0" ] && printf " done" || printf " failed"
+
+printf "\n:: Copying file systemd-bootx64.efi to /EFI/BOOT/loader.efi... "
+cp /boot/EFI/systemd/systemd-bootx64.efi /boot/EFI/BOOT/loader.efi
+[ $? = "0" ] && printf " done" || printf " failed"
+
+printf "\n:: Copying file PreLoader.efi to /boot/EFI/BOOT/BOOTx64.efi... "
+cp /usr/share/preloader-signed/PreLoader.efi /boot/EFI/BOOT/BOOTx64.efi
+[ $? = "0" ] && printf " done" || printf " failed"
+
