Add --file-size parameter

diff --git a/create-swap-file b/create-swap-file
--- a/create-swap-file
+++ b/create-swap-file
@@ -5,7 +5,7 @@
 
 help()
 {
-    printf "\nUsage: ${0} [--target-file|-t] [--help|-h]\n"
+    printf "\nUsage: ${0} [--target-file|-t] [--file-size|-f] [--help|-h]\n"
 }
 
 [ $# -eq 0 ] && help && exit 0
@@ -13,7 +13,8 @@ help()
 while [ $# -gt 0 ]
 do
     case "${1}" in
-        --target-file|-t) shift; export target_file="${1}" && break;;
+        --target-file|-t) shift; export target_file="${1}";;
+        --file-size|-f) shift; export file_size="${1}" && break;;
         --help|-h) help && exit 0;;
         *) help && exit 0;;
     esac
@@ -26,20 +27,24 @@ create_swapfile()
     [ $? = "1" ] && exit 1
     `which chmod` 0600 "${1}"
     [ $? = "1" ] && exit 1
-    `which dd` if=/dev/zero of="${1}" bs=1M
+    `which dd` if=/dev/zero of=${1} bs=1M count=${2} status=progress
     [ $? = "1" ] && exit 1
     `which mkswap` -L swap "${1}"
     [ $? = "1" ] && exit 1
     `swapon` "${1}"
     [ $? = "1" ] && exit 1
-    printf "\n/swapfile none swap sw 0 0\n" | tee -a "/etc/fstab"
+    printf "\n${1} none swap sw 0 0\n" | tee -a "/etc/fstab"
 }
 
 if [ ! -z "${target_file}" ]
 then
     if [ ! -f "${target_file}" ]
     then
-        create_swapfile "${target_file}"
+        if [ -z "${file_size}" ]
+        then
+            echo ":: ERROR: No size was specified for the swap file" && exit 1
+        fi
+        create_swapfile "${target_file}" "${file_size}"
     else
         echo ":: ERROR: ${target_file}: the file already exists" && exit 1
     fi
