Update vbox-kmst

diff --git a/vbox-kmst b/vbox-kmst
--- a/vbox-kmst
+++ b/vbox-kmst
@@ -2,52 +2,65 @@
 
 #
 # VirtualBox KMST (kernel module signing tool)
-# Created and developed by Liam Powell (gfelipe099)
+# Created by Ken Hoo (mrkenhoo)
 # vbox-kmst file
-# For GNU/Linux
 #
 
 # set config dir
-configDir="/root/.config/vbox-kmst/"
+configDir="${HOME}/.config/vbox-kmst"
 
-# check if running as root
-if [ "$(whoami)" != "root" ]; then
-    echo "You must execute this script as root"
-    exit 0
-    else
-        # create configuration directory if it does not exist
-        if [ ! -d ${configDir} ]; then
-            mkdir -p ${configDir}
-        fi
+if test `whoami` != "root"
+then
+    echo "Run this script as root" && exit 1
 fi
 
-if [ -z ${1} ]; then
-    echo "Specify an argument: import-key or sign-kernel-modules"
-    exit
-elif [ ${1} = "import-key" ]; then
-    # if the certificate does not exist create it and set proper permissions
-    if [ ! -f ${configDir}vbox.priv ]; then
-        echo "The private keys do not exist, creating it..."
-        openssl req -new -x509 -newkey rsa:2048 -keyout ${configDir}vbox.priv -outform DER -out ${configDir}vbox.der -nodes -days 36500 -subj "/CN=VirtualBox Secure Boot Key/" > /dev/null 2>&1
-        chmod 600 ${configDir}vbox.priv
-        echo "Please specify a password to import the key below:"
-        mokutil --import ${configDir}vbox.der
+if test ! -d "$configDir"
+then
+    mkdir -pv ${configDir}
+fi
+
+if test -z ${1}
+then
+    echo "Specify an argument: import-key or sign-kernel-modules" && exit 1
+fi
+
+while [ $# -eq 1 ]
+do
+    case "$1" in
+        --import-key|-i)
+            if test ! -f "${configDir}/vbox.priv"
+            then
+                echo "The private key do not exist, creating it..."
+                openssl req -new \
+                            -x509 \
+                            -newkey rsa:2048 \
+                            -keyout "${configDir}/vbox.priv" \
+                            -outform DER \
+                            -out "${configDir}/vbox.der" \
+                            -nodes \
+                            -days 36500 \
+                            -subj "/CN=VirtualBox Secure Boot Key/"
+                chmod 600 "${configDir}/vbox.priv"
+                echo "Please specify a password to import the key below:"
+                mokutil --import "${configDir}/vbox.der"
             else
                 echo "Please specify a password to import the key below:"
-                mokutil --import ${configDir}vbox.der
-    fi
-elif [ ${1} = "sign-kernel-modules" ]; then
-    if [ ! -f ${configDir}vbox.priv ]; then
-        echo "ERROR: sign-file: No private keys were found"
-        echo "Run import-key first"
-        exit
-        else
-            for vboxkmodule in $(dirname $(modinfo -n vboxdrv))/*.ko; do
-                echo "Signing kernel module ${vboxkmodule}..."
-                /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ${configDir}vbox.priv ${configDir}vbox.der "${vboxkmodule}" > /dev/null 2>&1
-            done
-    fi
-    else
-        echo "Unknown argument, try again with: import-key or sign-kernel-modules"
-        exit
-fi
+                mokutil --import "${configDir}/vbox.der"
+            fi
+        ;;
+        --sign-vbox-kernel-modules|-s)
+            if test ! -f "${configDir}/vbox.priv"
+            then
+                printf "ERROR: No private key(s) were found\nRun '--import-key' first\n" && return 1
+            else
+                for vboxkmodule in $(dirname $(modinfo -n vboxdrv))/*.ko; do
+                    echo "Signing kernel module ${vboxkmodule}..."
+                    /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ${configDir}vbox.priv ${configDir}vbox.der "${vboxkmodule}" > /dev/null 2>&1
+                done
+            fi
+        ;;
+        *)
+            echo "Invalid argument: $1" && exit 1
+        ;;
+    esac
+done
