Minor improvements

diff --git a/virtio-win-updater b/virtio-win-updater
--- a/virtio-win-updater
+++ b/virtio-win-updater
@@ -34,20 +34,21 @@ fi
 if [ -x "/usr/bin/curl" ]; then
     echo "==> Removing old ISO images..."
     for f in ${downloadDir}/*.iso; do
-    	rm -v "${f}"
+    	rm -iv "${f}"
     done
     echo ""; echo "==> Fetching the latest virtio-win ISO..."
     curl -L https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso > ${downloadDir}/virtio-stable.iso
     if [ -f "${downloadDir}/virtio-stable.iso" ]; then
-        echo "    --> Download successful"; echo ""
+        [ $? = 0 ] && echo "    --> Download successful" || echo "    --> There was an error"
     fi
 
     echo ""; echo "==> Fetching the stable virtio-win ISO..."
     curl -L https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso > ${downloadDir}/virtio-latest.iso
     if [ -f "${downloadDir}/virtio-latest.iso" ]; then
-        echo "    --> Download successful"; echo ""
+        [ $? = 0 ] && echo "    --> Download successful" || echo "    --> There was an error"
     fi
     else
         echo ":: ERROR: curl: command not found"
         exit 1
 fi
+
